services:
  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - auth
      - note
      - user
      - notification
 
  auth:
    build: ./services/auth
    ports:
      - "8081:8081"
    depends_on:
      - auth_db
      - rabbitmq
    environment:
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  note:
    build: ./services/note
    ports:
      - "8082:8082"
    depends_on:
      - note_db
      - rabbitmq
    environment:
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  user:
    build: ./services/user
    ports:
      - "8083:8083"
    depends_on:
      - user_db
      - rabbitmq
    environment:
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  notification:
    build: ./services/notification
    ports:
      - "8084:8084"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DBNAME=mydb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  auth_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  note_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=note_db
    volumes:
      - note_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  user_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--requirepass", "redis"]
    ports:
      - "6380:6379"

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  auth_db_data:
  note_db_data:
  user_db_data:
  mongo_data: