name: Microservices CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start all services
        run: docker compose up -d --build

      - name: Wait for services
        run: |
          echo "⏳ Waiting for services..."
          sleep 25
          docker ps

      - name: Install migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/local/bin

      - name: Run migrations
        run: make migrate

      - name: Stop all services
        if: always()
        run: docker compose down -v
